### ISSUE TITLE
Picking up 2 tips on a 1-channel chatterbox backend fails with unclear error 

### ISSUE THREAD

**Issue by naikymen** [PyLabRobot/pylabrobot#26]
I understand that this is not the intended usage, but naive users like me would (perhaps) land in this spot too, and get stuck.

![image](https://user-images.githubusercontent.com/3259326/229389029-ca648c59-d745-46a2-8022-8551fc1b646d.png)

It seems that PLR is not "realising" that the backend has 1 channel, and failing to use the second channel (with "Key 1").

I'd like to suggest adding a check to (at least) the `pick_up_tips` command, that handles this kind of inconsistency.

I'd suggest a spot but I'm have no clue where (yet). Let me know if I can help.

**Comment by naikymen** [comment]
A similar error appears with `aspirate`:

![image](https://user-images.githubusercontent.com/3259326/229389509-05df4843-44dd-46b8-86fe-3e502e15800d.png)

> Note that as a regular user of the R language, I tend to assume that all operations are vectorized. I expected `lh.aspirate(plate["A1:A2"], vols=[100.0, 50.0])` to mean "aspirate 100 from A1 into channel 1, and then 50 from A2 into channel 1."

**Comment by rickwierenga** [comment]
Thanks for reporting!

Fixed with https://github.com/PyLabRobot/pylabrobot/commit/48fb5cda5c888fea0f7257e73881974b829bbdd6.

**Comment by rickwierenga** [comment]
> Note that as a regular user of the R language, I tend to assume that all operations are vectorized. I expected lh.aspirate(plate["A1:A2"], vols=[100.0, 50.0]) to mean "aspirate 100 from A1 into channel 1, and then 50 from A2 into channel 1."

Correct

**Comment by naikymen** [comment]
Thank you Rick :) I'll be making some basic hardware tests this weekend on
a rudimentary backend.

Best!

**Comment by naikymen** [comment]
Hi Rick, sorry to bring this up again.



> > Note that as a regular user of the R language, I tend to assume that all operations are vectorized. I expected lh.aspirate(plate["A1:A2"], vols=[100.0, 50.0]) to mean "aspirate 100 from A1 into channel 1, and then 50 from A2 into channel 1."
> 
> Correct

I just want to check if that really is correct.

I am still getting the error:

![image](https://github.com/PyLabRobot/pylabrobot/assets/3259326/9e074c08-4a8b-40f3-b76b-21aabaf63cbb)

I think the vectorization in those functions is only channel-wise (i.e. to operate multi-channel pipettes).

**Comment by rickwierenga** [comment]
> aspirate 100 from A1 into channel 1, and then 50 from A2 into channel 1."
Channels are actually 0-indexed. Excuse the oversight: 100 from A1 into channel `0` :)

The error you see is because you're aspirating from two wells simultaneously (A1 and A2), whereas your backend `echo` only has one channel (as set by the `num_channels` property).

All atomic operations (`aspirate`, `pick_up_tips`, `drop_tips`, `dispense`) are expected to be executed simultaneously. Big robots like STAR support this up to 16 channels, although 8 is typical. If the user wants to do things separately, they should make two method calls on `lh`.

> sorry to bring this up again.

this is technically a separate issue, but in general please don't hesitate to tell me about anything you think can be improved.
